language: node_js
node_js:
- 16.20.2
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # MATTERMOST_HOOK_URL
  - secure: Ymu/aF2VgpOvdINM/ea64qMswZMCMgY6c9zKeY1rEqlI6jeBBNbYXmy2HlZjclrjWjqHOH/VBc3VAnQINrfxEZK8NDlkbJzmJ96FGJgCKftctkAhBZ0rSoVuc8qgdmMdFyR1Wtr0oWEKWoFio73Ly6dMvPHQjrYEYOV89l6Xv+8X6A/Pz7cNda/+yySQ9wR94KV6XhNJsWDc3cWFDnqzGBje8Vd+nmGAysBRq2B6PXuPfM7dpVHroocXQQueXriiOlvsIHcbNlC/0RWXkaC9aEYyHtqQgpmJw2rWBranhe9rqaj5LqGZsn9zEPKRA4vUpFbaNPI+0M96ETef4dsatpTVpAtJCStgAIrCWcrvGY7mYJ9wBnFzkwPoHdb9z1aNwNnyGn9sH0ifOrx34jo4ehkMdgT/8CfTNNXNm7lpMOJRGbbm56SJBkKjiaUa2NI8PMjlAuxDg2cOboCQg+DphtbjSFRX5GsdSC96vbxii32b6IpjmoHpKuhx6+GVMV5AJPShK5VumJRaeSNLVs3hhYqVmSex4i3Ny7IekhzvMYw5GBOz2HHpPwtXCdnVX6r6Ll2hVRYWzUQ1mt5Xqvz9spDwPfQSauC0JYTAWRvU/E+ACRTk+E9Ll2A5Bq41zvCR+QN0qVtIK2yFzx/nML38SsURPxka92QQGACx/E708Pw=
  # REGISTRY_TOKEN slug=caf editor=cozy space=default
  - secure: wiepRsCwJzxdW+YvPix7OJRDViroHgQPqYk4ZMsZaHo3kBo9vm/yCYe3a+bMYIm0p295f1yC9tWEdYjzA3L+g/zknPz7A3HA8cHnHhzCEF8o/aR7YgucdocPZCCThesq2nNV+m3ah/ev/Y3gTu929JeRyIgsGXq5yBS9JNZB/3AelLcF7iDp+vIOAEp5+3u0DPMJBqxMSzmezKLN8nMRU8bGg9+Ka8EjFk0Ma2kK0qsXbiPE/GSuWPHbslgQ1HeptdxMrN+N7kTuDbiW1bS/EjUZ6Cz9Axjbfv3HqUFpQiUfHdeKjVQivuuIbFaCIbbxJ64YBhGu4AAB1mz+uZb7d8Gt2906m+OmkI3iiBKLH9afd+yEZ/jMZkjs84lbvJIhH2+ppcQQqvdZmAxxcLjJXmDpek+idp5nPUkMv8n5IYnO/lVKFUV4Vs2L9DFnxgCi6WIyyxzPDT/xdONsS68H3beocHdFSx0ZBwrZMarK+hnl0Qauq58trf0+gZUBUFL1FRYgppZZC0CzMO+zpse+zjVzUkatWerd8PXCqbb1d57CNU/b+6Rtl0W5emVbFjj1B/SjW8KN1K6IYEVs81JsxIuHVM0wIvlsfMyDj4TMLBRh5S5vHCBOzPkkGlVmMk+mMY6dnpfXlUaM11vBINnToPb4FN6cfslU5xouiDc5fCs=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch:
    - master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
